version: '3.8'

services:
  web:
    build:
      context: .
      target: final
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    networks:
      - djangonetwork
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env.dev
    environment:
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=hello_django_dev
      - DATABASE_USER=hello_django
      - DATABASE_PASSWORD=hello_django
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - djangonetwork
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:

networks:
  djangonetwork: