apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
  namespace: tekton-pipelines
data:
  disable-affinity-assistant: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-events
  namespace: tekton-pipelines
data:
  formats: tektonv1
  sink: http://funckle.funckle.svc.cluster.local:80/webhooks/tekton