# Generated by Django 4.2.4 on 2023-08-20 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functions', '0002_functionversion_build_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='readme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='function',
            name='source_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('owner', 'slug')},
        ),
    ]
