# Generated by Django 4.2.4 on 2023-08-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_function_readme_function_source_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='functionversion',
            unique_together={('function', 'version')},
        ),
    ]
