apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - task/gcs-download/0.1/gcs-download.yaml
  - task/func-buildpacks/0.1/func-buildpacks.yaml
  - task/func-deploy/0.1/func-deploy.yaml
  - pipeline/func-pipeline/0.1/func-pipeline.yaml
  # - secrets.yaml these have to be create separately
  - serviceaccount.yaml