apiVersion: v1
kind: ServiceAccount
metadata:
  name:  funckle-func-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: funckle-func-deploy-knative
subjects:
- kind: ServiceAccount
  name: funckle-func-deploy
  namespace: default
roleRef:
  kind: ClusterRole
  name: knative-serving-namespaced-admin
  apiGroup: rbac.authorization.k8s.io