apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: funckle

resources:
- namespace.yaml
- config.yaml
- secret.yaml
- kservice.yaml
- database.yaml

images:
- name: europe-west2-docker.pkg.dev/hack-space-dev/funckle-user-functions/funckle
  newTag: 0.2.5
